export function getIcons(platform) {
  return platform === "PC"
    ? "fa-solid fa-desktop"
    : platform === "Xbox Series S/X"
    ? "fa-brands fa-xbox"
    : platform === "PlayStation 3"
    ? "fab fa-playstation"
    : platform === "Linux"
    ? "fa-brands fa-linux"
    : platform === "PlayStation 4"
    ? "fab fa-playstation"
    : platform === "macOS"
    ? "fa-brands fa-apple"
    : platform === "Android"
    ? "fa-brands fa-android"
    : platform === "Linux"
    ? "Linux"
    : platform === "Xbox One"
    ? "fa-brands fa-xbox"
    : platform === "Xbox 360"
    ? "fa-brands fa-xbox"
    : platform === "PlayStation 5"
    ? "fab fa-playstation"
    : platform === "Nintendo Switch"
    ? "Nintendo"
    : platform === "iOS"
    ? "fa-brands fa-apple"
    : platform === "n/a"
    ? ""
    : platform;
}
