export function shortenPlatforms(platform) {
  return platform === "PC"
    ? "PC"
    : platform === "Xbox Series S/X"
    ? "Xbox"
    : platform === "PlayStation 3"
    ? "PS3"
    : platform === "PlayStation 4"
    ? "PS4"
    : platform === "macOS"
    ? "mac"
    : platform === "Android"
    ? "Android"
    : platform === "Linux"
    ? "Linux"
    : platform === "Xbox One"
    ? "Xbox"
    : platform === "PlayStation 5"
    ? "PS5"
    : platform === "Nintendo Switch"
    ? "Nintendo"
    : platform === "n/a"
    ? ""
    : platform;
}
